name: Checks
on: [push]

jobs:
  checks:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
        # The Node.js version to configure
          node-version: 14
      - name: Install
        run: yarn
      - name: Lint
        run: yarn lint
